# Site settings
title: Liquid Chicken Advisory Council
email: setzer@liquidchicken.org
description: > # this means to ignore newlines until "baseurl:"
  Techniques, technologies, and clever ideas for Infrastructure Automation,
  Cloud Computing, and Application Delivery
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liquidchicken.org/" # the base hostname & protocol for your site
github_username: jekyll

jekyll-archives:
  enabled:
    - categories
    - tags
    - year
    - month
  layout: 'archive'
  layouts:
    tag: tag-archive-layout
    year: year-archive
    month: month-archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - pygments
  - jekyll-textile-converter
