# Site settings
title: Fluid Poultry Research Association
email: setzer@liquidchicken.org
description: > # this means to ignore newlines until "baseurl:"
  Techniques, technologies, and clever ideas for Infrastructure Automation,
  Cloud Computing, Agile, Continuous Integration, and Continuous Delivery.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liquidchicken.org/" # the base hostname & protocol for your site
github_username: jekyll

# Build settings
markdown: kramdown
highlighter: pygments
#gems:
#  - jekyll-mentions
#  - jemoji
#  - jekyll-redirect-from
#  - jekyll-sitemap
